version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-m", "app.bot.main"]
    volumes:
      - .:/app

volumes:
  postgres_data:
